# Generated by Django 4.2 on 2023-06-13 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ticketmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.ticketmodel'),
        ),
    ]
