# Generated by Django 4.2 on 2023-06-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_ticketmodel_reply_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
        migrations.RemoveField(
            model_name='ticketmodel',
            name='reply_to',
        ),
    ]
