# Generated by Django 4.2 on 2023-06-13 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_loginmodel_remove_ticketmodel_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
