# Generated by Django 4.2 on 2023-06-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_ticketmodel_send_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='send_telegram_alert',
            field=models.BooleanField(default=False),
        ),
    ]
